[template]
src           = "haproxy.cfg.tmpl"
dest          = "/usr/local/etc/haproxy/haproxy.cfg"
prefix        = "/services/haproxy"
keys          = [ "/frontend", "/backend", "/stats" ]
owner         = "root"
mode          = "0644"
check_cmd     = "/usr/sbin/haproxy -c -f {{ .src }}"
reload_cmd    = "echo restarting && /usr/bin/systemctl reload haproxy"
